name: Go Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        go: ["1.20.x", "1.21.x", "1.22.x", "1.23.x"]
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      DISPLAY: ":99.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
          version: 1.0

      - name: Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Test
        run: go test -p=1 -v ./...
